const Types = {
    LOGIN_CHECK: 'LOGIN_CHECK',
    LOGIN_HANDLE_CHANGE_USERNAME: 'LOGIN_HANDLE_CHANGE_USERNAME',
    LOGIN_HANDLE_CHANGE_PASSWORD: 'LOGIN_HANDLE_CHANGE_PASSWORD',
    DATA_CHANGE: 'DATA_CHANGE',
    DATA_UPDATE: 'DATA_UPDATE',
    CLUSTER_CHANGE: 'CLUSTER_CHANGE',
	SIZE_1_CHANGE: 'SIZE_1_CHANGE',
	SIZE_2_CHANGE: 'SIZE_2_CHANGE',
	NUMBER_ITERATIONS_CHANGE: 'NUMBER_ITERATIONS_CHANGE', 
	ACTIVATION_FUNCTION_CHANGE: 'ACTIVATION_FUNCTION_CHANGE', 
    ERROR_PARSE: 'ERROR_PARSE',
    OPTIONS_CHANGE_INDEPENDANT: 'OPTIONS_CHANGE_INDEPENDANT',
    OPTIONS_CHANGE_DEPENDANT: 'OPTIONS_CHANGE_DEPENDANT',
	OPTIONS_CHANGE_TYPE: 'OPTIONS_CHANGE_TYPE',
	OPTIONS_CHANGE_OUTPUT: 'OPTIONS_CHANGE_OUTPUT',
    ACCEPT: 'ACCEPT',
	ACCEPT_LOGISTIC: 'ACCEPT_LOGISTIC',
    ACCEPT_NEURAL_NETWORK: 'ACCEPT_NEURAL_NETWORK',
    CHANGE_CLUSTER_TYPE:'CHANGE_CLUSTER_TYPE'
}

export default Types;