const Types = {
    LOGIN_CHECK: 'LOGIN_CHECK',
    LOGIN_HANDLE_CHANGE_USERNAME: 'LOGIN_HANDLE_CHANGE_USERNAME',
    LOGIN_HANDLE_CHANGE_PASSWORD: 'LOGIN_HANDLE_CHANGE_PASSWORD',
    DATA_CHANGE: 'DATA_CHANGE',
    DATA_UPDATE: 'DATA_UPDATE',
    CLUSTER_CHANGE: 'CLUSTER_CHANGE',
    ERROR_PARSE: 'ERROR_PARSE',
    OPTIONS_CHANGE: 'OPTIONS_CHANGE',
    ACCEPT: 'ACCEPT'
}

export default Types;